### ISSUE TITLE
/var/lib/ mounts?

### ISSUE THREAD

**Issue by shishkin** [NobbZ/nixos-config#814]
Hi @NobbZ! I came across your config from a discussion on NixOS discourse. I hope you don't mind a quick question.

I noticed something in your setup that I don't understand. In the [paperless service](https://github.com/NobbZ/nixos-config/blob/3d25823a6d37dda1db309d6cc13f7b004c172a1f/nixos/configurations/mimas/paperless.nix#L11-L14) you write:

```nix
systemd.services.paperless-consumer.after = ["var-lib-paperless.mount"];
systemd.services.paperless-scheduler.after = ["var-lib-paperless.mount"];
systemd.services.paperless-task-queue.after = ["var-lib-paperless.mount"];
systemd.services.paperless-web.after = ["var-lib-paperless.mount"];
```

Is `"var-lib-paperless.mount"` the same mount defined in [hardware](https://github.com/NobbZ/nixos-config/blob/3d25823a6d37dda1db309d6cc13f7b004c172a1f/nixos/configurations/hardware/mimas.nix#L62-L66)? What is `/dev/pool/paperless` in that mount?

The background of my curiosity is trying to point systemd service's data directories somewhere else (e.g. mount point of another drive), but I don't understand how to do that in nix. I also don't want to create a partition for each service.

**Comment by NobbZ** [comment]
`mimas` has 2 LVM VGs connected. In a quite basic setup. Both are just formed from a single PV, though both contain several (thin) LVs. `pool` is the VG on the internal disk, while `usbpool` is on the external HDD:

```
❯ sudo pvs
[sudo] password for nmelzer: 
  PV         VG      Fmt  Attr PSize    PFree 
  /dev/sda3  pool    lvm2 a--  <914.51g 54.21g
  /dev/sdb3  usbpool lvm2 a--    <1.32t     0 
❯ sudo vgs
  VG      #PV #LV #SN Attr   VSize    VFree 
  pool      1  12   0 wz--n- <914.51g 54.21g
  usbpool   1   5   0 wz--n-   <1.32t     0 
❯ sudo lvs
  LV                    VG      Attr       LSize   Pool      Origin Data%  Meta%  Move Log Cpy%Sync Convert  docker                pool    Vwi-aotz--  40.00g thin-pool        4.19
  gitea                 pool    Vwi-aotz--  20.00g thin-pool        74.36
  grafana               pool    Vwi-aotz--  25.00g thin-pool        4.15
  home                  pool    -wi-ao---- 550.00g
  lvm-test              pool    Vwi-aotz--  20.00g thin-pool        2.21
  lvm-tmp               pool    Vwi-aotz--  50.00g thin-pool        15.98
  paperless             pool    Vwi-aotz--  50.00g thin-pool        3.00
  photoprism            pool    Vwi-a-tz--  25.00g thin-pool        2.08
  prometheus            pool    Vwi-aotz--  25.00g thin-pool        6.42
  root                  pool    -wi-ao----  10.00g
  store                 pool    -wi-ao---- 150.00g
  thin-pool             pool    twi-aotz-- 150.00g                  19.76  17.55
  random                usbpool Vwi-a-tz-- 100.00g usb-thin         25.68
  restic                usbpool Vwi-aotz-- 660.00g usb-thin         66.84
  ums                   usbpool Vwi-aotz-- 600.00g usb-thin         1.76
  usb-thin              usbpool twi-aotz--  <1.32t                  35.42  18.28
```

**Comment by shishkin** [comment]
I see. Thanks for the explanation. I wasn't familiar with LVM. Thin pools especially seem to be a nice feature.

I also came across [bind mounts](https://nixos.wiki/wiki/Filesystems#Bind_mounts). Those allow to mount e.g. `/var/lib/paperless` to `/data/apps/paperless`. And systemd seems to chown the directory, so `/data/apps` can be exclusively owned by root, while the service can write to it when running. What do you think of this approach?
